/**
 * Navbar (design.md 7.2) — public sticky navbar.
 * Default: `sticky top-0 z-50` in normal flow (react-dev.md navbar contract).
 * Page agents: do NOT edit this file or add nav-height offsets in pages.
 */
import { useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { Menu, X } from 'lucide-react';
import { useT } from '@/i18n';
import { roleDashboardPath, useDemoSession } from '@/data/demoSession';
import { cn } from '@/lib/utils';
import LanguageSwitcher from './LanguageSwitcher';
import MonogramAvatar from './shared/MonogramAvatar';

const LINKS: { to: string; key: string }[] = [
  { to: '/discover', key: 'nav.discover' },
  { to: '/rankings', key: 'nav.rankings' },
  { to: '/competitions', key: 'nav.competitions' },
  { to: '/opportunities', key: 'nav.opportunities' },
  { to: '/videos', key: 'nav.videos' },
  { to: '/match-scouting/demo-match', key: 'nav.scouting' },
  { to: '/athletes/erick-semedo', key: 'nav.athletes' },
  { to: '/clubs/atletico-achada', key: 'nav.clubs' },
  { to: '/scouts/scout-carlos-moniz', key: 'nav.scouts' },
];

export default function Navbar() {
  const t = useT();
  const navigate = useNavigate();
  const { isLoggedIn, persona, role } = useDemoSession();
  const [open, setOpen] = useState(false);

  return (
    <header className="sticky top-0 z-50 border-b border-line bg-white/85 backdrop-blur-md">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        {/* Logo + wordmark */}
        <Link to="/" className="flex shrink-0 items-center gap-2.5">
          <img src="/logo.png" alt="SportHub Scout" className="h-9 w-9 rounded-full" />
          <span className="leading-none">
            <span className="font-display text-[15px] font-extrabold tracking-tight text-ink-950">
              {t('brand.wordmarkA')} <span className="text-brand-500">{t('brand.wordmarkB')}</span>
            </span>
            <span className="mt-0.5 hidden text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-600 lg:block">
              by {t('brand.company')}
            </span>
          </span>
        </Link>

        {/* Center links (desktop) */}
        <nav className="hidden items-center gap-5 xl:flex" aria-label="main">
          {LINKS.map((l) => (
            <NavLink
              key={l.key}
              to={l.to}
              className={({ isActive }) =>
                cn(
                  'group relative py-1 text-[13.5px] font-medium transition-colors',
                  isActive ? 'text-ink-950' : 'text-ink-600 hover:text-ink-950',
                )
              }
            >
              {({ isActive }) => (
                <>
                  {t(l.key)}
                  <span
                    className={cn(
                      'absolute -bottom-0.5 left-0 h-0.5 bg-brand-500 transition-transform duration-200 origin-left',
                      isActive ? 'w-full scale-x-100' : 'w-full scale-x-0 group-hover:scale-x-100',
                    )}
                    aria-hidden
                  />
                </>
              )}
            </NavLink>
          ))}
        </nav>

        {/* Right side */}
        <div className="flex items-center gap-3">
          <LanguageSwitcher />
          <span className="hidden h-5 w-px bg-line sm:block" aria-hidden />
          {isLoggedIn && persona && role ? (
            <Link to={roleDashboardPath(role)} className="hidden items-center gap-2.5 sm:flex">
              <MonogramAvatar name={persona.name} size={32} />
              <span className="leading-tight">
                <span className="block max-w-[140px] truncate text-[13px] font-semibold text-ink-950">
                  {persona.name}
                </span>
                <span className="inline-flex items-center gap-1 rounded-full bg-brand-100 px-2 py-px text-[10px] font-bold uppercase tracking-wide text-brand-600">
                  {t(`roles.${role}`)}
                </span>
              </span>
            </Link>
          ) : (
            <div className="hidden items-center gap-2 sm:flex">
              <Link
                to="/auth"
                className="inline-flex h-10 items-center rounded-lg px-4 text-[14px] font-semibold text-ink-950 transition-colors hover:bg-paper-100"
              >
                {t('nav.signIn')}
              </Link>
              <Link
                to="/auth?mode=register"
                className="inline-flex h-10 items-center rounded-lg bg-brand-500 px-4 text-[14px] font-semibold text-white transition-all hover:bg-brand-600 active:scale-[0.97]"
              >
                {t('nav.createAccount')}
              </Link>
            </div>
          )}
          {/* Mobile hamburger */}
          <button
            type="button"
            onClick={() => setOpen(true)}
            aria-label={t('nav.openMenu')}
            className="rounded-lg p-2 text-ink-950 transition-colors hover:bg-paper-100 xl:hidden cursor-pointer"
          >
            <Menu size={22} aria-hidden />
          </button>
        </div>
      </div>

      {/* Mobile full-screen overlay menu */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-[60] flex flex-col bg-ink-950 px-6 py-5"
          >
            <div className="flex items-center justify-between">
              <img src="/logo.png" alt="" className="h-9 w-9 rounded-full" />
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label={t('nav.closeMenu')}
                className="rounded-lg p-2 text-white/70 transition-colors hover:bg-ink-800 hover:text-white cursor-pointer"
              >
                <X size={24} aria-hidden />
              </button>
            </div>
            <nav className="mt-10 flex flex-1 flex-col gap-1 overflow-y-auto" aria-label="mobile">
              {LINKS.map((l, i) => (
                <motion.div
                  key={l.key}
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.05 * i, duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
                >
                  <Link
                    to={l.to}
                    onClick={() => setOpen(false)}
                    className="block py-2 font-display text-[28px] font-extrabold text-white transition-colors hover:text-brand-500"
                  >
                    {t(l.key)}
                  </Link>
                </motion.div>
              ))}
              <motion.div
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.05 * LINKS.length, duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
              >
                <Link
                  to="/pricing"
                  onClick={() => setOpen(false)}
                  className="block py-2 font-display text-[28px] font-extrabold text-white transition-colors hover:text-brand-500"
                >
                  {t('nav.pricing')}
                </Link>
              </motion.div>
            </nav>
            <div className="flex items-center justify-between gap-3 border-t border-ink-700 pt-5">
              <LanguageSwitcher dark />
              {isLoggedIn && role ? (
                <button
                  type="button"
                  onClick={() => {
                    setOpen(false);
                    navigate(roleDashboardPath(role));
                  }}
                  className="inline-flex h-11 items-center rounded-lg bg-brand-500 px-5 font-semibold text-white cursor-pointer"
                >
                  {t('nav.dashboard')}
                </button>
              ) : (
                <div className="flex gap-2">
                  <Link
                    to="/auth"
                    onClick={() => setOpen(false)}
                    className="inline-flex h-11 items-center rounded-lg border border-ink-700 px-4 font-semibold text-white"
                  >
                    {t('nav.signIn')}
                  </Link>
                  <Link
                    to="/auth?mode=register"
                    onClick={() => setOpen(false)}
                    className="inline-flex h-11 items-center rounded-lg bg-brand-500 px-4 font-semibold text-white"
                  >
                    {t('nav.createAccount')}
                  </Link>
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </header>
  );
}
